version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-hotel
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: hotel_reservas
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
